### ISSUE TITLE
How to implement eb with avgpooling

### ISSUE THREAD

**Issue by rawatenator** [greydanus/excitationbp#1]
Hi Sam,

Great work! I just ran your code on VGG and think it's terrific. I haven't dug into the code yet but am wondering if you have a sense for how much work it would be to modify code so that it would work on a model with avg pooling instead of max pooling.

Thanks,

**Comment by greydanus** [comment]
Hey! I don't think it would take more than a few lines to write the autograd extension for avg pooling, but it requires understanding 1) PyTorch 2) excitation backprop and 3) the backward pass for average pooling inside and out. Check out the README about adding extensions in the [functions directory](https://github.com/greydanus/excitation_bp/tree/master/functions) to get started.

**Comment by rawatenator** [comment]
Thanks for the reply, I started looking into this over the weekend but am hitting a wall trying to get the original code to work with cuda. any reason why it need to be done on the cpu?

(I'm attaching a modified version of your tutorial file with the cuda change. It causes a CUDNN_STATUS_BAD_PARAM error for reasons I haven't been able to figure out)

[tutorial.ipynb.zip](https://github.com/greydanus/excitation_bp/files/1445074/tutorial.ipynb.zip)

**Comment by greydanus** [comment]
It doesn't need to be done with CPU. I wrote it for CPU because that was simplest for me. Honestly I don't know much about how things would change to support GPU. Yesterday I did commit a new version of the repo which supports the latest PyTorch and can be installed as a package. If you haven't moved on, it might be worth checking out. Sorry for the delay :P
